//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingBufferPlus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RingBufferPlus.MessagesResource", typeof(MessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias can&apos;t be null.
        /// </summary>
        internal static string BuildErr_Alias {
            get {
                return ResourceManager.GetString("BuildErr_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoScaler can&apos;t be null.
        /// </summary>
        internal static string BuildErr_AutoScaler {
            get {
                return ResourceManager.GetString("BuildErr_AutoScaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory can&apos;t be null.
        /// </summary>
        internal static string BuildErr_Factory {
            get {
                return ResourceManager.GetString("BuildErr_Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HealthCheck can&apos;t be null.
        /// </summary>
        internal static string BuildErr_HealthCheck {
            get {
                return ResourceManager.GetString("BuildErr_HealthCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Accquire must be greater than zero.
        /// </summary>
        internal static string BuildErr_IdleAccquire {
            get {
                return ResourceManager.GetString("BuildErr_IdleAccquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial buffer must be greater than 1.
        /// </summary>
        internal static string BuildErr_InitialBuffer {
            get {
                return ResourceManager.GetString("BuildErr_InitialBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval AutoScaler must be greater than zero.
        /// </summary>
        internal static string BuildErr_IntervalAutoScaler {
            get {
                return ResourceManager.GetString("BuildErr_IntervalAutoScaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Interval FailureState must be greater than zero..
        /// </summary>
        internal static string BuildErr_IntervalFailureState {
            get {
                return ResourceManager.GetString("BuildErr_IntervalFailureState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval HealthCheck must be greater than zero.
        /// </summary>
        internal static string BuildErr_IntervalHealthCheck {
            get {
                return ResourceManager.GetString("BuildErr_IntervalHealthCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval Report must be greater than zero.
        /// </summary>
        internal static string BuildErr_IntervalReport {
            get {
                return ResourceManager.GetString("BuildErr_IntervalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval warmup must be greater than zero.
        /// </summary>
        internal static string BuildErr_IntervalWarmup {
            get {
                return ResourceManager.GetString("BuildErr_IntervalWarmup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Function can&apos;t be null.
        /// </summary>
        internal static string BuildErr_LinkedFunction {
            get {
                return ResourceManager.GetString("BuildErr_LinkedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxAvaliable must be greater than 1.
        /// </summary>
        internal static string BuildErr_MaxAvaliable {
            get {
                return ResourceManager.GetString("BuildErr_MaxAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Maximum Capacity({1}) must be greater  or equal to than Initial Capacity({2}).
        /// </summary>
        internal static string BuildErr_MaxInit {
            get {
                return ResourceManager.GetString("BuildErr_MaxInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Maximum Capacity({1}) must be greater  or equal to than Minimum Capacity({2}).
        /// </summary>
        internal static string BuildErr_MaxMin {
            get {
                return ResourceManager.GetString("BuildErr_MaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinAvaliable must be greater than 1.
        /// </summary>
        internal static string BuildErr_MinAvaliable {
            get {
                return ResourceManager.GetString("BuildErr_MinAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Minimum Capacity({1}) must be less than  or equal to Initial Capacity({2}).
        /// </summary>
        internal static string BuildErr_MinInit {
            get {
                return ResourceManager.GetString("BuildErr_MinInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User function Policy must be null.
        /// </summary>
        internal static string BuildErr_PolicyMustBeNull {
            get {
                return ResourceManager.GetString("BuildErr_PolicyMustBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User function Policy can&apos;t be null.
        /// </summary>
        internal static string BuildErr_PolicyNull {
            get {
                return ResourceManager.GetString("BuildErr_PolicyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report can&apos;t be null.
        /// </summary>
        internal static string BuildErr_Report {
            get {
                return ResourceManager.GetString("BuildErr_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout Available must be greater than zero.
        /// </summary>
        internal static string BuildErr_TimeoutAccquire {
            get {
                return ResourceManager.GetString("BuildErr_TimeoutAccquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error: {0}.
        /// </summary>
        internal static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias {0}.
        /// </summary>
        internal static string Log_Alias {
            get {
                return ResourceManager.GetString("Log_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Warmup AutoScaler delay {1}.
        /// </summary>
        internal static string Log_AutoScalerDelay {
            get {
                return ResourceManager.GetString("Log_AutoScalerDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Failure State!.
        /// </summary>
        internal static string Log_FailureState {
            get {
                return ResourceManager.GetString("Log_FailureState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Fixed AutoScaler {1}.
        /// </summary>
        internal static string Log_FixedAutoScaler {
            get {
                return ResourceManager.GetString("Log_FixedAutoScaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Idle Accquire {1}.
        /// </summary>
        internal static string Log_IdleAccquire {
            get {
                return ResourceManager.GetString("Log_IdleAccquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Initial Capacity {1}.
        /// </summary>
        internal static string Log_InitialCapacity {
            get {
                return ResourceManager.GetString("Log_InitialCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Interval AutoScaler {1}.
        /// </summary>
        internal static string Log_IntervalAutoScaler {
            get {
                return ResourceManager.GetString("Log_IntervalAutoScaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} FailureState {1}.
        /// </summary>
        internal static string Log_IntervalFailureState {
            get {
                return ResourceManager.GetString("Log_IntervalFailureState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Interval HealthCheck {1}.
        /// </summary>
        internal static string Log_IntervalHealthCheck {
            get {
                return ResourceManager.GetString("Log_IntervalHealthCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Interval Report {1}.
        /// </summary>
        internal static string Log_IntervalReport {
            get {
                return ResourceManager.GetString("Log_IntervalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Maximum Capacity {1}.
        /// </summary>
        internal static string Log_MaximumCapacity {
            get {
                return ResourceManager.GetString("Log_MaximumCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Minimum Capacity {1}.
        /// </summary>
        internal static string Log_MinimumCapacity {
            get {
                return ResourceManager.GetString("Log_MinimumCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} Thread State {2}.
        /// </summary>
        internal static string Log_ThreadState {
            get {
                return ResourceManager.GetString("Log_ThreadState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Timeout Accquire {1}.
        /// </summary>
        internal static string Log_TimeoutAccquire {
            get {
                return ResourceManager.GetString("Log_TimeoutAccquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} AutoScaler({1}) Try {2} to {3}.
        /// </summary>
        internal static string Log_TryAutoScaler {
            get {
                return ResourceManager.GetString("Log_TryAutoScaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} Error!.
        /// </summary>
        internal static string Log_UserfunError {
            get {
                return ResourceManager.GetString("Log_UserfunError", resourceCulture);
            }
        }
    }
}
